# Generated by Django 2.1.7 on 2019-03-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscrubers',
            new_name='Subscribers',
        ),
    ]
